import React, {useEffect} from 'react';

// Algolia Experiences search, generated by Algolia's "Get Started" flow
// (app QG2QVTAJUS). The library mounts its search UI into the #autocomplete
// container once loaded. The apiKey is a public search-only key — safe to
// commit, same as classic DocSearch keys.
//
// This overrides the navbar's default (Noop) SearchBar, so the search box
// appears at the right of the navbar automatically.
const EXPERIENCES_SRC =
  'https://cdn.jsdelivr.net/npm/@algolia/experiences/dist/experiences.js' +
  '?appId=QG2QVTAJUS&apiKey=bdfb2f5d47836caca79c2ffa8fb93bcb' +
  '&experienceId=QG2QVTAJUS&env=prod';

const SCRIPT_ID = 'algolia-experiences';

export default function SearchBar(): React.JSX.Element {
  useEffect(() => {
    // Load the library only once. The navbar (and this container) persist
    // across client-side navigation, so the script must not be re-appended.
    if (document.getElementById(SCRIPT_ID)) {
      return;
    }
    const script = document.createElement('script');
    script.id = SCRIPT_ID;
    script.src = EXPERIENCES_SRC;
    script.async = true;
    // Injected here (after mount) so #autocomplete already exists in the DOM
    // when the library initializes.
    document.body.appendChild(script);
  }, []);

  return <div id="autocomplete" />;
}
